# model
## encoder
in_channels : 14 # feat d
order : ("z", "z-trans", "hilbert", "hilbert-trans")
stride : (2, 2, 2, 2)
enc_depths : (2, 2, 2, 6, 2)
enc_channels : (32, 64, 128, 256, 512)
enc_dim : 128
enc_num_head : (2, 4, 8, 16, 32)
enc_patch_size : (1024, 1024, 1024, 1024, 1024)
dec_depths : (2, 2, 2, 2)
dec_channels : (128, 128, 256, 256)
dec_num_head : (4, 4, 8, 16)
dec_patch_size : (1024, 1024, 1024, 1024)
mlp_ratio : 4
qkv_bias : True
qk_scale : 0.25
attn_drop : 0.0
proj_drop : 0.0
drop_path : 0.3
pre_norm : True
shuffle_orders : True
enable_rpe : False
enable_flash : False
upcast_attention : False
upcast_softmax : False
cls_mode : False
pdnorm_bn : False
pdnorm_ln : False
pdnorm_decouple : False
pdnorm_adaptive : False
pdnorm_affine : True
pdnorm_conditions : ("ScanNet", "S3DIS", "Structured3D")

## RVQ
embed_dim: 512   # vq embed dim
n_embed: 16384  # vq num embeddings
embed_loss_weight: 1.0
embed_levels: 2  # rvq levels
stochasticity: 0.1
embed_share: True  # share embeddings across rvq levels
code_decay: 0.99  # code decay for vq
cluster_size: 64

# trainer
wandb_main: False
suffix: ''
experiment: ex1  # experiment name
seed: null
save_epoch: 1  # save every n epoch
sanity_steps: 1  # sanity steps before the run
val_check_percent: 1.0  # check this proportion of val set when evaluation runs
val_check_interval: 1  # run evaluation every x% of the train set steps
resume: null  # resume from a checkpoint
logger: tb
overfit: False  # overfitting dataloaders

# data
dataset: 'shapenet'
category: '02871439'
grid_size: 0.01
batch_size: 1
num_workers: 1 
max_rotation: 30
scale_range: (0.8, 1.2)
color_jitter: 0.1
density_dropout: 0.1


# optimizer
lr: 1e-4 # max learning rate
force_lr: null
max_epoch: 2000 # total number of training iterations
weight_decay: 1e-1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0 # clip gradients at this value, or disable if == 0.0
warmup_steps: 2000 # how many steps to warm up for
min_lr: 6e-5 # minimum learning rate, should be ~= learning_rate/10 per Chinchilla
gradient_accumulation_steps: 2

# other
num_tokens: 64
ce_output: True
pos_enc_weight: 0.1
skip_quant: True
coord_bins: 64
color_bins: 64
opacity_bins: 64
scale_bins: 64
rot_bins: 64