wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.33.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.21
    start_time: 1738747795.657313
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 63
      - 77
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 63
      - 77
      3:
      - 7
      - 13
      - 14
      - 23
      4: 3.9.21
      5: 0.13.4
      6: 4.33.0
      8:
      - 3
      - 8
